export const SOCKET__INITIATE = "SOCKET__INITIATE";
export const SOCKET__UPDATE_FRIENDS = "SOCKET__UPDATE_FRIENDS";
export const SOCKET__UPDATE_MESSAGE = "SOCKET__UPDATE_MESSAGE";

export const HOME__GET_FRIENDS__PROGRESS = "HOME__GET_FRIENDS__PROGRESS";
export const HOME__GET_FRIENDS__SUCCESS = "HOME__GET_FRIENDS__SUCCESS";
export const HOME__GET_FRIENDS__ERROR = "HOME__GET_FRIENDS__ERROR";
export const HOME__SET_ACTIVE_FRIEND = "HOME__SET_ACTIVE_FRIEND";

export const HOME__GET_MESSAGES__PROGRESS = "HOME__GET_MESSAGES__PROGRESS";
export const HOME__GET_MESSAGES__SUCCESS = "HOME__GET_MESSAGES__SUCCESS";
export const HOME__GET_MESSAGES__ERROR = "HOME__GET_MESSAGES__ERROR";
