export const AUTH__CHANGE_VIEW = "AUTH__CHANGE_VIEW";

export const AUTH__LOG_IN__PROGRESS = "AUTH__LOG_IN__PROGRESS";
export const AUTH__LOG_IN__SUCCESS = "AUTH__LOG_IN__SUCCESS";
export const AUTH__LOG_IN__ERROR = "AUTH__LOG_IN__ERROR";

export const AUTH__REGISTER__PROGRESS = "AUTH__REGISTER__PROGRESS";
export const AUTH__REGISTER__SUCCESS = "AUTH__REGISTER__SUCCESS";
export const AUTH__REGISTER__ERROR = "AUTH__REGISTER__ERROR";

export const AUTH__LOG_OUT__PROGRESS = "AUTH__LOG_OUT__PROGRESS";
export const AUTH__LOG_OUT__SUCCESS = "AUTH__LOG_OUT__SUCCESS";
export const AUTH__LOG_OUT__ERROR = "AUTH__LOG_OUT__ERROR";

export const AUTH__FORGOT_PASSWORD__PROGRESS =
  "AUTH__FORGOT_PASSWORD__PROGRESS";
export const AUTH__FORGOT_PASSWORD__SUCCESS = "AUTH__FORGOT_PASSWORD__SUCCESS";
export const AUTH__FORGOT_PASSWORD__ERROR = "AUTH__FORGOT_PASSWORD__ERROR";
